### PR TITLE
Sanitizing downloaded filename

### PR DESCRIPTION
**Pull request by simonavril**
fixing, Sanitizing downloaded filename when using 'date' query.

### CODE REVIEW

**Comment by simonavril** [comment]
test:
from pyGoogleTrendsCsvDownloader import pyGoogleTrendsCsvDownloader r = pyGoogleTrendsCsvDownloader(login, password') r.get_csv(cat='0-958',date='1/2006 12m', geo='US-ME-500')
error:
Traceback (most recent call last): File "test.py", line 6, in <module> r.get_csv(cat='0-958',date='1/2006 12m', geo='US-ME-500') File "/home/savril/workspace/google-trends-csv-downloader/pyGoogleTrendsCsvDownloader.py", line 134, in get_csv myFile = open('trends_%s.csv' % '_'.join(['%s-%s' % (key, value) for (key, value) in kwargs.items()]), 'w') IOError: [Errno 2] No such file or directory: 'trends_date-1/2006 12m_geo-US-ME-500_cat-0-958.csv'

**Comment by pedrofaustino** [comment]
Hi @simonavril 

Thanks for the PR. I would like to use a more generic approach. Perhaps you could use Django's `slugify` function available [here](https://github.com/django/django/blob/master/django/utils/text.py#L436)?

```
def slugify(value):
    """
    Converts to lowercase, removes non-word characters (alphanumerics and
    underscores) and converts spaces to hyphens. Also strips leading and
    trailing whitespace.
    """
    import unicodedata, re
    value = unicodedata.normalize('NFKD', value).encode('ascii', 'ignore').decode('ascii')
    value = re.sub('[^\w\s-]', '', value).strip().lower()
    return unicode(re.sub('[-\s]+', '-', value))
```

One example:

```
>>> str = u" john's portrait/|\() é 2004.   "
>>> slugify(str)
u'johns-portrait-e-2004'
```

SO thread pointing to the right direction [here](http://stackoverflow.com/a/295466)

**Comment by simonavril** [comment]
@pedrofaustino : Let me know if that wasn't what you had in mind.

**Comment by pedrofaustino** [comment]
Thanks @simonavril , just merged.

**Pull request merged**
